### ISSUE TITLE
Add some block previews

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-bootstrap4#21]
Based on https://github.com/luyadev/luya-module-cms/pull/148

**Comment by nadar** [comment]
Which blocks do you think need a preview? I don't think it makes sense for every block.

**Comment by boehsermoe** [comment]
E.g. carousel ?
<img width="400" alt="screenshot 2018-11-11 at 07 28 54" src="https://user-images.githubusercontent.com/2466744/48309916-8898ec80-e583-11e8-8abb-0fbb2de24df8.png">

**Comment by nadar** [comment]
sounds good

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
