### ISSUE TITLE
Not all bootstrap options can be set in carousel

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-bootstrap4#31]
### What steps will reproduce the problem?
Some options do not allow all possibilities

### What is the expected result?
All options can be set as intended

### What do you get instead? (A Screenshot can help us a lot!)
Not working as expected

### Additional infos
I will check it asap.

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
