### ISSUE TITLE
How to run "./luya install"?

### ISSUE THREAD

**Issue by johnsnook** [luyadev/luya-bootstrap4#9]
In your installation instructions, you list this as needed after the composer install. 

I don't find this script file anywhere, nor a console controller command.

**Comment by nadar** [comment]
Hi @johnsnook In order to use the LUYA specific content (blocks, tags, etc), you must run a LUYA application. 

+ How to install LUYA => https://luya.io/guide/install
+ Installation Video => https://www.youtube.com/watch?v=Ybq878PMe_U
+ Or a LUYA bootstrap 4 application starter with gulp/npm workflow => https://github.com/luyadev/luya-kickstarter-bootstrap4

If you just want to have the Bootstrap 4 Widgets for your Yii 2 Application you can just add luyadev/luya-bootstrap4 to your composer.json, run `composer update` and start using the Widgets - there is no need to install anything.

Where did you find the `./luya install` instructions? The `luya` bin file is located in the vendor/bin folder (only when running a LUYA application - as mentioned at the beginn.

**Comment by dev7ch** [comment]
https://github.com/luyadev/luya-bootstrap4/blob/master/README.md here in the readme of is repo `./luya`  command used

**Comment by nadar** [comment]
@dev7ch yes - but not install
